/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-10-02 11:53:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.backend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import org.hibernate.SessionFactory;
import lk.verdana.ecom.util.HibernateUtil;
import org.hibernate.Session;
import lk.verdana.ecom.entity.Product;
import lk.verdana.ecom.entity.Category;
import java.util.List;

public final class editproduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/Users/Tharuka/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.0/jakarta.servlet.jsp.jstl-3.0.0.jar", Long.valueOf(1692679976646L));
    _jspx_dependants.put("jar:file:/C:/Users/Tharuka/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.0/jakarta.servlet.jsp.jstl-3.0.0.jar!/META-INF/c-1_2.tld", Long.valueOf(1649416098000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("lk.verdana.ecom.util.HibernateUtil");
    _jspx_imports_classes.add("lk.verdana.ecom.entity.Category");
    _jspx_imports_classes.add("lk.verdana.ecom.entity.Product");
    _jspx_imports_classes.add("org.hibernate.SessionFactory");
    _jspx_imports_classes.add("org.hibernate.Session");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\" />\r\n");
      out.write("    <title>Edit Product - Dashboard Admin Template</title>\r\n");
      out.write("    <link\r\n");
      out.write("            rel=\"stylesheet\"\r\n");
      out.write("            href=\"https://fonts.googleapis.com/css?family=Roboto:400,700\"\r\n");
      out.write("    />\r\n");
      out.write("    <!-- https://fonts.google.com/specimen/Roboto -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin-assets/css/fontawesome.min.css\" />\r\n");
      out.write("    <!-- https://fontawesome.com/ -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin-assets/jquery-ui-datepicker/jquery-ui.min.css\" type=\"text/css\" />\r\n");
      out.write("    <!-- http://api.jqueryui.com/datepicker/ -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin-assets/css/bootstrap.min.css\" />\r\n");
      out.write("    <!-- https://getbootstrap.com/ -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin-assets/css/templatemo-style.css\">\r\n");
      out.write("    <!--\r\n");
      out.write("	Product Admin CSS Template\r\n");
      out.write("	https://templatemo.com/tm-524-product-admin\r\n");
      out.write("	-->\r\n");
      out.write("</head>\r\n");

    SessionFactory sessionFactory = HibernateUtil.getSessionFactory();
    Session openSession = sessionFactory.openSession();



//    List<Category> category = openSession.createQuery("select category from Category category", Category.class).getResultList();
//    pageContext.setAttribute("category", category);
    String productIds = (String) request.getAttribute("productId");
    int productId = Integer.parseInt(productIds);



    Product product = openSession.createQuery("SELECT product FROM Product product WHERE product.id = :productId", Product.class)
            .setParameter("productId", productId)
            .uniqueResult();
    pageContext.setAttribute("product", product);

    List<Category> category = openSession.createQuery("select category from Category category", Category.class).getResultList();
    pageContext.setAttribute("category", category);


      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar navbar-expand-xl\">\r\n");
      out.write("    <div class=\"container h-100\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"index.html\">\r\n");
      out.write("            <h1 class=\"tm-site-title mb-0\">Product Admin</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        <button\r\n");
      out.write("                class=\"navbar-toggler ml-auto mr-0\"\r\n");
      out.write("                type=\"button\"\r\n");
      out.write("                data-toggle=\"collapse\"\r\n");
      out.write("                data-target=\"#navbarSupportedContent\"\r\n");
      out.write("                aria-controls=\"navbarSupportedContent\"\r\n");
      out.write("                aria-expanded=\"false\"\r\n");
      out.write("                aria-label=\"Toggle navigation\"\r\n");
      out.write("        >\r\n");
      out.write("            <i class=\"fas fa-bars tm-nav-icon\"></i>\r\n");
      out.write("        </button>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("            <ul class=\"navbar-nav mx-auto h-100\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"index.html\">\r\n");
      out.write("                        <i class=\"fas fa-tachometer-alt\"></i> Dashboard\r\n");
      out.write("                        <span class=\"sr-only\">(current)</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a\r\n");
      out.write("                            class=\"nav-link dropdown-toggle\"\r\n");
      out.write("                            href=\"#\"\r\n");
      out.write("                            id=\"navbarDropdown\"\r\n");
      out.write("                            role=\"button\"\r\n");
      out.write("                            data-toggle=\"dropdown\"\r\n");
      out.write("                            aria-haspopup=\"true\"\r\n");
      out.write("                            aria-expanded=\"false\"\r\n");
      out.write("                    >\r\n");
      out.write("                        <i class=\"far fa-file-alt\"></i>\r\n");
      out.write("                        <span> Reports <i class=\"fas fa-angle-down\"></i> </span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"#\">Daily Report</a>\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"#\">Weekly Report</a>\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"#\">Yearly Report</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link active\" href=\"products.html\">\r\n");
      out.write("                        <i class=\"fas fa-shopping-cart\"></i> Products\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"accounts.html\">\r\n");
      out.write("                        <i class=\"far fa-user\"></i> Accounts\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a\r\n");
      out.write("                            class=\"nav-link dropdown-toggle\"\r\n");
      out.write("                            href=\"#\"\r\n");
      out.write("                            id=\"navbarDropdown\"\r\n");
      out.write("                            role=\"button\"\r\n");
      out.write("                            data-toggle=\"dropdown\"\r\n");
      out.write("                            aria-haspopup=\"true\"\r\n");
      out.write("                            aria-expanded=\"false\"\r\n");
      out.write("                    >\r\n");
      out.write("                        <i class=\"fas fa-cog\"></i>\r\n");
      out.write("                        <span> Settings <i class=\"fas fa-angle-down\"></i> </span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"#\">Profile</a>\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"#\">Billing</a>\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"#\">Customize</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"navbar-nav\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link d-block\" href=\"login.html\">\r\n");
      out.write("                        Admin, <b>Logout</b>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("<div class=\"container tm-mt-big tm-mb-big\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-xl-9 col-lg-10 col-md-12 col-sm-12 mx-auto\">\r\n");
      out.write("            <div class=\"tm-bg-primary-dark tm-block tm-block-h-auto\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                        <h2 class=\"tm-block-title d-inline-block\">Edit Product</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row tm-edit-product-row\">\r\n");
      out.write("                    <div class=\"col-xl-6 col-lg-6 col-md-12\">\r\n");
      out.write("                        <div class=\"form-group mb-3\">\r\n");
      out.write("                            <label\r\n");
      out.write("                                    for=\"id\"\r\n");
      out.write("                            >Product id\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <input\r\n");
      out.write("                                    id=\"id\"\r\n");
      out.write("                                    name=\"id\"\r\n");
      out.write("                                    type=\"text\"\r\n");
      out.write("                                    disabled\r\n");
      out.write("                                    value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("                                    class=\"form-control validate\"\r\n");
      out.write("                            />\r\n");
      out.write("                        </div>\r\n");
      out.write("                            <div class=\"form-group mb-3\">\r\n");
      out.write("                                <label\r\n");
      out.write("                                        for=\"name\"\r\n");
      out.write("                                >Product Name\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <input\r\n");
      out.write("                                        id=\"name\"\r\n");
      out.write("                                        name=\"name\"\r\n");
      out.write("                                        type=\"text\"\r\n");
      out.write("                                        value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("                                        class=\"form-control validate\"\r\n");
      out.write("                                />\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group mb-3\">\r\n");
      out.write("                                <label\r\n");
      out.write("                                        for=\"description\"\r\n");
      out.write("                                >Description</label\r\n");
      out.write("                                >\r\n");
      out.write("                                <textarea\r\n");
      out.write("                                        class=\"form-control validate tm-small\"\r\n");
      out.write("                                        rows=\"5\"\r\n");
      out.write("                                        id=\"description\"\r\n");
      out.write("                                        required\r\n");
      out.write("\r\n");
      out.write("                                >");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.description}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group mb-3\">\r\n");
      out.write("                                <label\r\n");
      out.write("                                        for=\"category\"\r\n");
      out.write("                                >Category</label\r\n");
      out.write("                                >\r\n");
      out.write("                                <select id=\"category\"\r\n");
      out.write("                                        class=\"custom-select tm-select-accounts\"\r\n");
      out.write("\r\n");
      out.write("                                >\r\n");
      out.write("                                    <option value=\"1\" selected>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.category.name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</option>\r\n");
      out.write("\r\n");
      out.write("                                    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"form-group mb-3 col-xs-12 col-sm-6\">\r\n");
      out.write("                                    <label\r\n");
      out.write("                                            for=\"expire_date\"\r\n");
      out.write("                                    >price\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                    <input\r\n");
      out.write("                                            id=\"price\"\r\n");
      out.write("\r\n");
      out.write("                                            type=\"text\"\r\n");
      out.write("                                            value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.price}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("                                            class=\"form-control validate\"\r\n");
      out.write("                                            data-large-mode=\"true\"\r\n");
      out.write("                                    />\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-6 col-lg-6 col-md-12 mx-auto mb-4\">\r\n");
      out.write("                        <div class=\"tm-product-img-edit mx-auto\">\r\n");
      out.write("                            <img src=\"img/product-image.jpg\" alt=\"Product image\" class=\"img-fluid d-block mx-auto\">\r\n");
      out.write("                            <i\r\n");
      out.write("                                    class=\"fas fa-cloud-upload-alt tm-upload-icon\"\r\n");
      out.write("                                    onclick=\"document.getElementById('fileInput').click();\"\r\n");
      out.write("                            ></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"custom-file mt-3 mb-3\">\r\n");
      out.write("                            <input id=\"fileInput\" type=\"file\" style=\"display:none;\" />\r\n");
      out.write("                            <input\r\n");
      out.write("                                    type=\"button\"\r\n");
      out.write("                                    class=\"btn btn-primary btn-block mx-auto\"\r\n");
      out.write("                                    value=\"CHANGE IMAGE NOW\"\r\n");
      out.write("                                    onclick=\"document.getElementById('fileInput').click();\"\r\n");
      out.write("                            />\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                        <button onclick=\"updateProduct()\" class=\"btn btn-primary btn-block text-uppercase\">Update Now</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<footer class=\"tm-footer row tm-mt-small\">\r\n");
      out.write("    <div class=\"col-12 font-weight-light\">\r\n");
      out.write("        <p class=\"text-center text-white mb-0 px-4 small\">\r\n");
      out.write("            Copyright &copy; <b>2018</b> All rights reserved.\r\n");
      out.write("\r\n");
      out.write("            Design: <a rel=\"nofollow noopener\" href=\"https://templatemo.com\" class=\"tm-footer-link\">Template Mo</a>\r\n");
      out.write("        </p>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin-assets/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<!-- https://jquery.com/download/ -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin-assets/jquery-ui-datepicker/jquery-ui.min.js\"></script>\r\n");
      out.write("<!-- https://jqueryui.com/download/ -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin-assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- https://getbootstrap.com/ -->\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("    function updateProduct(){\r\n");
      out.write("        let id = document.getElementById(\"id\").value;\r\n");
      out.write("        let name = document.getElementById(\"name\").value;\r\n");
      out.write("        let price = document.getElementById(\"price\").value;\r\n");
      out.write("        let description = document.getElementById(\"description\").value;\r\n");
      out.write("        let category = document.getElementById(\"category\").value;\r\n");
      out.write("        alert(id)\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("adminpanel/updateproductprocess',{\r\n");
      out.write("            method:'post',\r\n");
      out.write("            headers:{\r\n");
      out.write("                'Content-Type': 'application/json'\r\n");
      out.write("            },\r\n");
      out.write("            body:JSON.stringify({\r\n");
      out.write("                id:id,\r\n");
      out.write("                name:name,\r\n");
      out.write("                price:price,\r\n");
      out.write("                description:description,\r\n");
      out.write("                category:category\r\n");
      out.write("            })\r\n");
      out.write("        }).then(response => {\r\n");
      out.write("            if (response.ok) {\r\n");
      out.write("                alert(\"saved\");\r\n");
      out.write("                window.location = BASE_URL+\"adminpanel\"\r\n");
      out.write("                return response.json();\r\n");
      out.write("            } else {\r\n");
      out.write("                throw new Error('Request failed with status: ' + response.status);\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("            .then(text => console.log(text));\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/backend/editproduct.jsp(209,36) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("category");
      // /WEB-INF/views/backend/editproduct.jsp(209,36) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/backend/editproduct.jsp(209,36) '${category}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${category}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                        <option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("\r\n");
            out.write("                                    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
