/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-09-28 15:37:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.backend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/Tharuka/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
    _jspx_dependants.put("file:/C:/Users/Tharuka/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1692244463551L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_layout_005fextends_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005fextends_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:extends
    lk.callidora.jsp.inheritance.ExtendsTag _jspx_th_layout_005fextends_005f0 = new lk.callidora.jsp.inheritance.ExtendsTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fextends_005f0);
    try {
      _jspx_th_layout_005fextends_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/backend/index.jsp(3,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fextends_005f0.setName("adminbase");
      _jspx_th_layout_005fextends_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_layout_005fextends_005f0, null));
      _jspx_th_layout_005fextends_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fextends_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f0 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f0);
    try {
      _jspx_th_layout_005fput_005f0.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f0.setParent(_jspx_parent);
      // /WEB-INF/views/backend/index.jsp(5,4) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setBlock("adminContent");
      // /WEB-INF/views/backend/index.jsp(5,4) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setType("REPLACE");
      _jspx_th_layout_005fput_005f0.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_layout_005fput_005f0, null));
      _jspx_th_layout_005fput_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f0);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private jakarta.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, jakarta.servlet.jsp.JspContext jspContext, jakarta.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fput_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write('\r');
      out.write('\n');
      return false;
    }
    public boolean invoke1( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col\">\r\n");
      out.write("                    <p class=\"text-white mt-5 mb-5\">Welcome back, <b>Admin</b></p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- row -->\r\n");
      out.write("            <div class=\"row tm-content-row\">\r\n");
      out.write("                <div class=\"col-sm-12 col-md-12 col-lg-6 col-xl-6 tm-block-col\">\r\n");
      out.write("                    <div class=\"tm-bg-primary-dark tm-block\">\r\n");
      out.write("                        <h2 class=\"tm-block-title\">Latest Hits</h2>\r\n");
      out.write("                        <canvas id=\"lineChart\"></canvas>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-12 col-md-12 col-lg-6 col-xl-6 tm-block-col\">\r\n");
      out.write("                    <div class=\"tm-bg-primary-dark tm-block\">\r\n");
      out.write("                        <h2 class=\"tm-block-title\">Performance</h2>\r\n");
      out.write("                        <canvas id=\"barChart\"></canvas>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-12 col-md-12 col-lg-6 col-xl-6 tm-block-col\">\r\n");
      out.write("                    <div class=\"tm-bg-primary-dark tm-block tm-block-taller\">\r\n");
      out.write("                        <h2 class=\"tm-block-title\">Storage Information</h2>\r\n");
      out.write("                        <div id=\"pieChartContainer\">\r\n");
      out.write("                            <canvas id=\"pieChart\" class=\"chartjs-render-monitor\" width=\"200\" height=\"200\"></canvas>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-12 col-md-12 col-lg-6 col-xl-6 tm-block-col\">\r\n");
      out.write("                    <div class=\"tm-bg-primary-dark tm-block tm-block-taller tm-block-overflow\">\r\n");
      out.write("                        <h2 class=\"tm-block-title\">Notification List</h2>\r\n");
      out.write("                        <div class=\"tm-notification-items\">\r\n");
      out.write("                            <div class=\"media tm-notification-item\">\r\n");
      out.write("                                <div class=\"tm-gray-circle\"><img src=\"img/notification-01.jpg\" alt=\"Avatar Image\" class=\"rounded-circle\"></div>\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                    <p class=\"mb-2\"><b>Jessica</b> and <b>6 others</b> sent you new <a href=\"#\"\r\n");
      out.write("                                                                                                       class=\"tm-notification-link\">product updates</a>. Check new orders.</p>\r\n");
      out.write("                                    <span class=\"tm-small tm-text-color-secondary\">6h ago.</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"media tm-notification-item\">\r\n");
      out.write("                                <div class=\"tm-gray-circle\"><img src=\"img/notification-02.jpg\" alt=\"Avatar Image\" class=\"rounded-circle\"></div>\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                    <p class=\"mb-2\"><b>Oliver Too</b> and <b>6 others</b> sent you existing <a href=\"#\"\r\n");
      out.write("                                                                                                               class=\"tm-notification-link\">product updates</a>. Read more reports.</p>\r\n");
      out.write("                                    <span class=\"tm-small tm-text-color-secondary\">6h ago.</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"media tm-notification-item\">\r\n");
      out.write("                                <div class=\"tm-gray-circle\"><img src=\"img/notification-03.jpg\" alt=\"Avatar Image\" class=\"rounded-circle\"></div>\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                    <p class=\"mb-2\"><b>Victoria</b> and <b>6 others</b> sent you <a href=\"#\"\r\n");
      out.write("                                                                                                    class=\"tm-notification-link\">order updates</a>. Read order information.</p>\r\n");
      out.write("                                    <span class=\"tm-small tm-text-color-secondary\">6h ago.</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"media tm-notification-item\">\r\n");
      out.write("                                <div class=\"tm-gray-circle\"><img src=\"img/notification-01.jpg\" alt=\"Avatar Image\" class=\"rounded-circle\"></div>\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                    <p class=\"mb-2\"><b>Laura Cute</b> and <b>6 others</b> sent you <a href=\"#\"\r\n");
      out.write("                                                                                                      class=\"tm-notification-link\">product records</a>.</p>\r\n");
      out.write("                                    <span class=\"tm-small tm-text-color-secondary\">6h ago.</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"media tm-notification-item\">\r\n");
      out.write("                                <div class=\"tm-gray-circle\"><img src=\"img/notification-02.jpg\" alt=\"Avatar Image\" class=\"rounded-circle\"></div>\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                    <p class=\"mb-2\"><b>Samantha</b> and <b>6 others</b> sent you <a href=\"#\"\r\n");
      out.write("                                                                                                    class=\"tm-notification-link\">order stuffs</a>.</p>\r\n");
      out.write("                                    <span class=\"tm-small tm-text-color-secondary\">6h ago.</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"media tm-notification-item\">\r\n");
      out.write("                                <div class=\"tm-gray-circle\"><img src=\"img/notification-03.jpg\" alt=\"Avatar Image\" class=\"rounded-circle\"></div>\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                    <p class=\"mb-2\"><b>Sophie</b> and <b>6 others</b> sent you <a href=\"#\"\r\n");
      out.write("                                                                                                  class=\"tm-notification-link\">product updates</a>.</p>\r\n");
      out.write("                                    <span class=\"tm-small tm-text-color-secondary\">6h ago.</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"media tm-notification-item\">\r\n");
      out.write("                                <div class=\"tm-gray-circle\"><img src=\"img/notification-01.jpg\" alt=\"Avatar Image\" class=\"rounded-circle\"></div>\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                    <p class=\"mb-2\"><b>Lily A</b> and <b>6 others</b> sent you <a href=\"#\"\r\n");
      out.write("                                                                                                  class=\"tm-notification-link\">product updates</a>.</p>\r\n");
      out.write("                                    <span class=\"tm-small tm-text-color-secondary\">6h ago.</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"media tm-notification-item\">\r\n");
      out.write("                                <div class=\"tm-gray-circle\"><img src=\"img/notification-02.jpg\" alt=\"Avatar Image\" class=\"rounded-circle\"></div>\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                    <p class=\"mb-2\"><b>Amara</b> and <b>6 others</b> sent you <a href=\"#\"\r\n");
      out.write("                                                                                                 class=\"tm-notification-link\">product updates</a>.</p>\r\n");
      out.write("                                    <span class=\"tm-small tm-text-color-secondary\">6h ago.</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"media tm-notification-item\">\r\n");
      out.write("                                <div class=\"tm-gray-circle\"><img src=\"img/notification-03.jpg\" alt=\"Avatar Image\" class=\"rounded-circle\"></div>\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                    <p class=\"mb-2\"><b>Cinthela</b> and <b>6 others</b> sent you <a href=\"#\"\r\n");
      out.write("                                                                                                    class=\"tm-notification-link\">product updates</a>.</p>\r\n");
      out.write("                                    <span class=\"tm-small tm-text-color-secondary\">6h ago.</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-12 tm-block-col\">\r\n");
      out.write("                    <div class=\"tm-bg-primary-dark tm-block tm-block-taller tm-block-scroll\">\r\n");
      out.write("                        <h2 class=\"tm-block-title\">Orders List</h2>\r\n");
      out.write("                        <table class=\"table\">\r\n");
      out.write("                            <thead>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th scope=\"col\">ORDER NO.</th>\r\n");
      out.write("                                <th scope=\"col\">STATUS</th>\r\n");
      out.write("                                <th scope=\"col\">OPERATORS</th>\r\n");
      out.write("                                <th scope=\"col\">LOCATION</th>\r\n");
      out.write("                                <th scope=\"col\">DISTANCE</th>\r\n");
      out.write("                                <th scope=\"col\">START DATE</th>\r\n");
      out.write("                                <th scope=\"col\">EST DELIVERY DUE</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("                            <tbody>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th scope=\"row\"><b>#122349</b></th>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <div class=\"tm-status-circle moving\">\r\n");
      out.write("                                    </div>Moving\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td><b>Oliver Trag</b></td>\r\n");
      out.write("                                <td><b>London, UK</b></td>\r\n");
      out.write("                                <td><b>485 km</b></td>\r\n");
      out.write("                                <td>16:00, 12 NOV 2018</td>\r\n");
      out.write("                                <td>08:00, 18 NOV 2018</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th scope=\"row\"><b>#122348</b></th>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <div class=\"tm-status-circle pending\">\r\n");
      out.write("                                    </div>Pending\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td><b>Jacob Miller</b></td>\r\n");
      out.write("                                <td><b>London, UK</b></td>\r\n");
      out.write("                                <td><b>360 km</b></td>\r\n");
      out.write("                                <td>11:00, 10 NOV 2018</td>\r\n");
      out.write("                                <td>04:00, 14 NOV 2018</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th scope=\"row\"><b>#122347</b></th>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <div class=\"tm-status-circle cancelled\">\r\n");
      out.write("                                    </div>Cancelled\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td><b>George Wilson</b></td>\r\n");
      out.write("                                <td><b>London, UK</b></td>\r\n");
      out.write("                                <td><b>340 km</b></td>\r\n");
      out.write("                                <td>12:00, 22 NOV 2018</td>\r\n");
      out.write("                                <td>06:00, 28 NOV 2018</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th scope=\"row\"><b>#122346</b></th>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <div class=\"tm-status-circle moving\">\r\n");
      out.write("                                    </div>Moving\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td><b>William Aung</b></td>\r\n");
      out.write("                                <td><b>London, UK</b></td>\r\n");
      out.write("                                <td><b>218 km</b></td>\r\n");
      out.write("                                <td>15:00, 10 NOV 2018</td>\r\n");
      out.write("                                <td>09:00, 14 NOV 2018</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th scope=\"row\"><b>#122345</b></th>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <div class=\"tm-status-circle pending\">\r\n");
      out.write("                                    </div>Pending\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td><b>Harry Ryan</b></td>\r\n");
      out.write("                                <td><b>London, UK</b></td>\r\n");
      out.write("                                <td><b>280 km</b></td>\r\n");
      out.write("                                <td>15:00, 11 NOV 2018</td>\r\n");
      out.write("                                <td>09:00, 17 NOV 2018</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th scope=\"row\"><b>#122344</b></th>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <div class=\"tm-status-circle pending\">\r\n");
      out.write("                                    </div>Pending\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td><b>Michael Jones</b></td>\r\n");
      out.write("                                <td><b>London, UK</b></td>\r\n");
      out.write("                                <td><b>218 km</b></td>\r\n");
      out.write("                                <td>18:00, 12 OCT 2018</td>\r\n");
      out.write("                                <td>06:00, 18 OCT 2018</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th scope=\"row\"><b>#122343</b></th>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <div class=\"tm-status-circle moving\">\r\n");
      out.write("                                    </div>Moving\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td><b>Timmy Davis</b></td>\r\n");
      out.write("                                <td><b>London, UK</b></td>\r\n");
      out.write("                                <td><b>218 km</b></td>\r\n");
      out.write("                                <td>12:00, 10 OCT 2018</td>\r\n");
      out.write("                                <td>08:00, 18 OCT 2018</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th scope=\"row\"><b>#122342</b></th>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <div class=\"tm-status-circle moving\">\r\n");
      out.write("                                    </div>Moving\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td><b>Oscar Phyo</b></td>\r\n");
      out.write("                                <td><b>London, UK</b></td>\r\n");
      out.write("                                <td><b>420 km</b></td>\r\n");
      out.write("                                <td>15:30, 06 OCT 2018</td>\r\n");
      out.write("                                <td>09:30, 16 OCT 2018</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th scope=\"row\"><b>#122341</b></th>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <div class=\"tm-status-circle moving\">\r\n");
      out.write("                                    </div>Moving\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td><b>Charlie Brown</b></td>\r\n");
      out.write("                                <td><b>London, UK</b></td>\r\n");
      out.write("                                <td><b>300 km</b></td>\r\n");
      out.write("                                <td>11:00, 10 OCT 2018</td>\r\n");
      out.write("                                <td>03:00, 14 OCT 2018</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th scope=\"row\"><b>#122340</b></th>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <div class=\"tm-status-circle cancelled\">\r\n");
      out.write("                                    </div>Cancelled\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td><b>Wilson Cookies</b></td>\r\n");
      out.write("                                <td><b>London, UK</b></td>\r\n");
      out.write("                                <td><b>218 km</b></td>\r\n");
      out.write("                                <td>17:30, 12 OCT 2018</td>\r\n");
      out.write("                                <td>08:30, 22 OCT 2018</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th scope=\"row\"><b>#122339</b></th>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <div class=\"tm-status-circle moving\">\r\n");
      out.write("                                    </div>Moving\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td><b>Richard Clamon</b></td>\r\n");
      out.write("                                <td><b>London, UK</b></td>\r\n");
      out.write("                                <td><b>150 km</b></td>\r\n");
      out.write("                                <td>15:00, 12 OCT 2018</td>\r\n");
      out.write("                                <td>09:20, 26 OCT 2018</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    ");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws jakarta.servlet.jsp.JspException
    {
      jakarta.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(jakarta.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
        }
        jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof jakarta.servlet.jsp.SkipPageException)
            throw (jakarta.servlet.jsp.SkipPageException) e;
        throw new jakarta.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
