/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-09-24 11:44:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend.include;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- footer -->\r\n");
      out.write("<div class=\"footer-top section-padding bg-black\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-2 col-sm-4 col-6 mb-sm-20\">\r\n");
      out.write("                <div class=\"icon-box\"><span class=\"text-light-green\"><i class=\"flaticon-credit-card-1\"></i></span>\r\n");
      out.write("                    <span class=\"text-custom-white\">100% Payment<br>Secured</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-2 col-sm-4 col-6 mb-sm-20\">\r\n");
      out.write("                <div class=\"icon-box\"><span class=\"text-light-green\"><i class=\"flaticon-wallet-1\"></i></span>\r\n");
      out.write("                    <span class=\"text-custom-white\">Support lots<br> of Payments</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-2 col-sm-4 col-6 mb-sm-20\">\r\n");
      out.write("                <div class=\"icon-box\"><span class=\"text-light-green\"><i class=\"flaticon-help\"></i></span>\r\n");
      out.write("                    <span class=\"text-custom-white\">24 hours / 7 days<br>Support</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-2 col-sm-4 col-6\">\r\n");
      out.write("                <div class=\"icon-box\"><span class=\"text-light-green\"><i class=\"flaticon-truck\"></i></span>\r\n");
      out.write("                    <span class=\"text-custom-white\">Free Delivery<br>with $50</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-2 col-sm-4 col-6\">\r\n");
      out.write("                <div class=\"icon-box\"><span class=\"text-light-green\"><i class=\"flaticon-guarantee\"></i></span>\r\n");
      out.write("                    <span class=\"text-custom-white\">Best Price<br>Guaranteed</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-2 col-sm-4 col-6\">\r\n");
      out.write("                <div class=\"icon-box\"><span class=\"text-light-green\"><i class=\"flaticon-app-file-symbol\"></i></span>\r\n");
      out.write("                    <span class=\"text-custom-white\">Mobile Apps<br>Ready</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<footer class=\"section-padding bg-light-theme pt-0 u-line bg-black\">\r\n");
      out.write("    <div class=\"u-line instagram-slider swiper-container\">\r\n");
      out.write("        <ul class=\"hm-list hm-instagram swiper-wrapper\">\r\n");
      out.write("            <li class=\"swiper-slide\">\r\n");
      out.write("                <a href=\"#\"><img src=\"assets/img/restaurants/250x200/insta-3.jpg\" alt=\"instagram\"></a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"swiper-slide\">\r\n");
      out.write("                <a href=\"#\"><img src=\"assets/img/restaurants/250x200/insta-1.jpg\" alt=\"instagram\"></a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"swiper-slide\">\r\n");
      out.write("                <a href=\"#\"><img src=\"assets/img/restaurants/250x200/insta-2.jpg\" alt=\"instagram\"></a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"swiper-slide\">\r\n");
      out.write("                <a href=\"#\"><img src=\"assets/img/restaurants/250x200/insta-4.jpg\" alt=\"instagram\"></a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"swiper-slide\">\r\n");
      out.write("                <a href=\"#\"><img src=\"assets/img/restaurants/250x200/insta-5.jpg\" alt=\"instagram\"></a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"swiper-slide\">\r\n");
      out.write("                <a href=\"#\"><img src=\"assets/img/restaurants/250x200/insta-6.jpg\" alt=\"instagram\"></a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"swiper-slide\">\r\n");
      out.write("                <a href=\"#\"><img src=\"assets/img/restaurants/250x200/insta-7.jpg\" alt=\"instagram\"></a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"swiper-slide\">\r\n");
      out.write("                <a href=\"#\"><img src=\"assets/img/restaurants/250x200/insta-8.jpg\" alt=\"instagram\"></a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-xl col-lg-4 col-md-4 col-sm-6\">\r\n");
      out.write("                <div class=\"footer-contact\">\r\n");
      out.write("                    <h6 class=\"text-custom-white\">Need Help</h6>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li class=\"fw-600\"><span class=\"text-light-white\">Call Us</span> <a href=\"tel:\"\r\n");
      out.write("                                                                                            class=\"text-custom-white\">+(347)\r\n");
      out.write("                            123 456 789</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"fw-600\"><span class=\"text-light-white\">Email Us</span> <a href=\"mailto:\"\r\n");
      out.write("                                                                                             class=\"text-custom-white\">demo@domain.com</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"fw-600\"><span class=\"text-light-white\">Join our twitter</span> <a href=\"#\"\r\n");
      out.write("                                                                                                     class=\"text-custom-white\">@munchbox</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"fw-600\"><span class=\"text-light-white\">Join our instagram</span> <a href=\"#\"\r\n");
      out.write("                                                                                                       class=\"text-custom-white\">@munchbox</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-xl col-lg-4 col-md-4 col-sm-6\">\r\n");
      out.write("                <div class=\"footer-links\">\r\n");
      out.write("                    <h6 class=\"text-custom-white\">Get to Know Us</h6>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\" class=\"text-light-white fw-600\">About Us</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"#\" class=\"text-light-white fw-600\">Blog</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"#\" class=\"text-light-white fw-600\">Socialize</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"#\" class=\"text-light-white fw-600\">Munchbox</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"#\" class=\"text-light-white fw-600\">Perks</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-xl col-lg-4 col-md-4 col-sm-6\">\r\n");
      out.write("                <div class=\"footer-links\">\r\n");
      out.write("                    <h6 class=\"text-custom-white\">Let Us Help You</h6>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\" class=\"text-light-white fw-600\">Account Details</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"#\" class=\"text-light-white fw-600\">Order History</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"#\" class=\"text-light-white fw-600\">Find restaurant</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"#\" class=\"text-light-white fw-600\">Login</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"#\" class=\"text-light-white fw-600\">Track order</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-xl col-lg-4 col-md-4 col-sm-6\">\r\n");
      out.write("                <div class=\"footer-links\">\r\n");
      out.write("                    <h6 class=\"text-custom-white\">Doing Business</h6>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\" class=\"text-light-white fw-600\">Suggest an Idea</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"#\" class=\"text-light-white fw-600\">Be a Partner restaurant</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"#\" class=\"text-light-white fw-600\">Create an Account</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"#\" class=\"text-light-white fw-600\">Help</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-xl col-lg-4 col-md-4 col-sm-6\">\r\n");
      out.write("                <div class=\"footer-links\">\r\n");
      out.write("                    <h6 class=\"text-custom-white\">Download Apps</h6>\r\n");
      out.write("                    <div class=\"appimg\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"assets/img/playstore.jpg\" class=\"img-fluid\" alt=\"app logo\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"appimg\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"assets/img/appstore.jpg\" class=\"img-fluid\" alt=\"app logo\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-xl col-lg-4 col-md-4 col-sm-6\">\r\n");
      out.write("                <div class=\"footer-contact\">\r\n");
      out.write("                    <h6 class=\"text-custom-white\">Newsletter</h6>\r\n");
      out.write("                    <form class=\"subscribe_form\">\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("                            <input type=\"text\" class=\"form-control form-control-submit\" name=\"email\"\r\n");
      out.write("                                   placeholder=\"Enter your email\">\r\n");
      out.write("                            <span class=\"input-group-btn\">\r\n");
      out.write("                      <button class=\"btn btn-second btn-submit\" type=\"button\"><i\r\n");
      out.write("                              class=\"fas fa-paper-plane\"></i></button>\r\n");
      out.write("                 </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-12\">\r\n");
      out.write("                <div class=\"ft-social-media\">\r\n");
      out.write("                    <h6 class=\"text-center text-light-black\">Follow us</h6>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"#\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"#\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"#\"><i class=\"fab fa-pinterest-p\"></i></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"#\"><i class=\"fab fa-youtube\"></i></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("<div class=\"copyright bg-black\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-4\">\r\n");
      out.write("                <div class=\"payment-logo mb-md-20\"><span class=\"text-light-white fs-14 mr-3\">We are accept</span>\r\n");
      out.write("                    <div class=\"payemt-icon\">\r\n");
      out.write("                        <img src=\"assets/img/card-front.jpg\" alt=\"#\">\r\n");
      out.write("                        <img src=\"assets/img/visa.jpg\" alt=\"#\">\r\n");
      out.write("                        <img src=\"assets/img/amex-card-front.png\" alt=\"#\">\r\n");
      out.write("                        <img src=\"assets/img/mastercard.png\" alt=\"#\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4 text-center medewithlove align-self-center\">\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4\">\r\n");
      out.write("                <div class=\"copyright-text\"><span class=\"text-light-white\"><a href=\"templateshub.net\">Templates Hub</a> </span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- footer -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
