/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-09-28 06:18:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend.include;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("    <header class=\"full-width\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-12 mainNavCol\">\r\n");
      out.write("                    <!-- logo -->\r\n");
      out.write("                    <div class=\"logo mainNavCol\">\r\n");
      out.write("                        <a href=\"index-2.html\">\r\n");
      out.write("                            <img src=\"assets/img/logo.png\" class=\"img-fluid\" alt=\"Logo\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- logo -->\r\n");
      out.write("                    <div class=\"main-search mainNavCol\">\r\n");
      out.write("                        <form class=\"main-search search-form full-width\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <!-- location picker -->\r\n");
      out.write("                                <div class=\"col-lg-6 col-md-5\">\r\n");
      out.write("                                    <a href=\"#\" class=\"delivery-add p-relative\"> <span class=\"icon\"><i\r\n");
      out.write("                                            class=\"fas fa-map-marker-alt\"></i></span>\r\n");
      out.write("                                        <span class=\"address\">Brooklyn, NY</span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <div class=\"location-picker\">\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" placeholder=\"Enter a new address\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- location picker -->\r\n");
      out.write("                                <!-- search -->\r\n");
      out.write("                                <div class=\"col-lg-6 col-md-7\">\r\n");
      out.write("                                    <div class=\"search-box padding-10\">\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" placeholder=\"Pizza, Burger, Chinese\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- search -->\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"right-side fw-700 mainNavCol\">\r\n");
      out.write("                        <div class=\"gem-points\">\r\n");
      out.write("                            <a href=\"#\"> <i class=\"fas fa-concierge-bell\"></i>\r\n");
      out.write("                                <span>Order Now</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"catring parent-megamenu\">\r\n");
      out.write("                            <a href=\"#\"> <span>Pages <i class=\"fas fa-caret-down\"></i></span>\r\n");
      out.write("                                <i class=\"fas fa-bars\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"megamenu\">\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col-sm-12\">\r\n");
      out.write("                                        <div class=\"row\">\r\n");
      out.write("                                            <div class=\"col-lg-4 col-md-5\">\r\n");
      out.write("                                                <div class=\"ex-collection-box h-100\">\r\n");
      out.write("                                                    <a href=\"#\">\r\n");
      out.write("                                                        <img src=\"assets/img/nav-1.jpg\"\r\n");
      out.write("                                                             class=\"img-fluid full-width h-100\" alt=\"image\">\r\n");
      out.write("                                                    </a>\r\n");
      out.write("                                                    <div class=\"category-type overlay padding-15\"><a\r\n");
      out.write("                                                            href=\"restaurant.html\" class=\"category-btn\">Top rated</a>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-lg-8 col-md-7\">\r\n");
      out.write("                                                <div class=\"row\">\r\n");
      out.write("                                                    <div class=\"col-lg-3 col-sm-6\">\r\n");
      out.write("                                                        <div class=\"menu-style\">\r\n");
      out.write("                                                            <div class=\"menu-title\">\r\n");
      out.write("                                                                <h6 class=\"cat-name\"><a href=\"#\"\r\n");
      out.write("                                                                                        class=\"text-light-black\">Home\r\n");
      out.write("                                                                    Pages</a></h6>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <ul>\r\n");
      out.write("                                                                <li class=\"active\"><a href=\"index-2.html\"\r\n");
      out.write("                                                                                      class=\"text-light-white fw-500\">Landing\r\n");
      out.write("                                                                    Page</a>\r\n");
      out.write("                                                                </li>\r\n");
      out.write("                                                                <li><a href=\"homepage-1.html\"\r\n");
      out.write("                                                                       class=\"text-light-white fw-500\">Home Page 1</a>\r\n");
      out.write("                                                                </li>\r\n");
      out.write("                                                                <li><a href=\"homepage-2.html\"\r\n");
      out.write("                                                                       class=\"text-light-white fw-500\">Home Page 2</a>\r\n");
      out.write("                                                                </li>\r\n");
      out.write("                                                                <li><a href=\"homepage-3.html\"\r\n");
      out.write("                                                                       class=\"text-light-white fw-500\">Home Page 3</a>\r\n");
      out.write("                                                                </li>\r\n");
      out.write("                                                                <li><a href=\"homepage-4.html\"\r\n");
      out.write("                                                                       class=\"text-light-white fw-500\">Home Page 4</a>\r\n");
      out.write("                                                                </li>\r\n");
      out.write("                                                            </ul>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"col-lg-3 col-sm-6\">\r\n");
      out.write("                                                        <div class=\"menu-style\">\r\n");
      out.write("                                                            <div class=\"menu-title\">\r\n");
      out.write("                                                                <h6 class=\"cat-name\"><a href=\"#\"\r\n");
      out.write("                                                                                        class=\"text-light-black\">Inner\r\n");
      out.write("                                                                    Pages</a></h6>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <ul>\r\n");
      out.write("                                                                <li><a href=\"blog.html\" class=\"text-light-white fw-500\">Blog\r\n");
      out.write("                                                                    Grid View</a>\r\n");
      out.write("                                                                </li>\r\n");
      out.write("                                                                <li><a href=\"blog-style-2.html\"\r\n");
      out.write("                                                                       class=\"text-light-white fw-500\">Blog Grid View\r\n");
      out.write("                                                                    2</a>\r\n");
      out.write("                                                                </li>\r\n");
      out.write("                                                                <li><a href=\"blog-details.html\"\r\n");
      out.write("                                                                       class=\"text-light-white fw-500\">Blog Details</a>\r\n");
      out.write("                                                                </li>\r\n");
      out.write("                                                                <li><a href=\"ex-deals.html\"\r\n");
      out.write("                                                                       class=\"text-light-white fw-500\">Ex Deals</a>\r\n");
      out.write("                                                                </li>\r\n");
      out.write("                                                                <li><a href=\"about.html\"\r\n");
      out.write("                                                                       class=\"text-light-white fw-500\">About Us</a>\r\n");
      out.write("                                                                </li>\r\n");
      out.write("                                                            </ul>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"col-lg-3 col-sm-6\">\r\n");
      out.write("                                                        <div class=\"menu-style\">\r\n");
      out.write("                                                            <div class=\"menu-title\">\r\n");
      out.write("                                                                <h6 class=\"cat-name\"><a href=\"#\"\r\n");
      out.write("                                                                                        class=\"text-light-black\">Related\r\n");
      out.write("                                                                    Pages</a></h6>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <ul>\r\n");
      out.write("                                                                <li><a href=\"restaurant.html\"\r\n");
      out.write("                                                                       class=\"text-light-white fw-500\">Restaurant</a>\r\n");
      out.write("                                                                <li><a href=\"restaurant-style-1.html\"\r\n");
      out.write("                                                                       class=\"text-light-white fw-500\">Restaurant 1</a>\r\n");
      out.write("                                                                </li>\r\n");
      out.write("                                                                <li><a href=\"restaurant-style-2.html\"\r\n");
      out.write("                                                                       class=\"text-light-white fw-500\">Restaurant 2</a>\r\n");
      out.write("                                                                </li>\r\n");
      out.write("                                                                <li><a href=\"add-restaurant.html\"\r\n");
      out.write("                                                                       class=\"text-light-white fw-500\">Add\r\n");
      out.write("                                                                    Restaurant</a>\r\n");
      out.write("                                                                </li>\r\n");
      out.write("                                                                <li><a href=\"list-view.html\"\r\n");
      out.write("                                                                       class=\"text-light-white fw-500\">List View</a>\r\n");
      out.write("                                                                </li>\r\n");
      out.write("                                                            </ul>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"col-lg-3 col-sm-6\">\r\n");
      out.write("                                                        <div class=\"menu-style\">\r\n");
      out.write("                                                            <div class=\"menu-title\">\r\n");
      out.write("                                                                <h6 class=\"cat-name\"><a href=\"#\"\r\n");
      out.write("                                                                                        class=\"text-light-black\">Additional\r\n");
      out.write("                                                                    Pages</a></h6>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <ul>\r\n");
      out.write("                                                                <li><a href=\"login.html\"\r\n");
      out.write("                                                                       class=\"text-light-white fw-500\">Login</a>\r\n");
      out.write("                                                                </li>\r\n");
      out.write("                                                                <li><a href=\"register.html\"\r\n");
      out.write("                                                                       class=\"text-light-white fw-500\">Sign-up</a>\r\n");
      out.write("                                                                </li>\r\n");
      out.write("                                                                <li><a href=\"checkout.html\"\r\n");
      out.write("                                                                       class=\"text-light-white fw-500\">Checkout</a>\r\n");
      out.write("                                                                </li>\r\n");
      out.write("                                                                <li><a href=\"order-details.html\"\r\n");
      out.write("                                                                       class=\"text-light-white fw-500\">Order Details</a>\r\n");
      out.write("                                                                </li>\r\n");
      out.write("                                                                <li><a href=\"geo-locator.html\"\r\n");
      out.write("                                                                       class=\"text-light-white fw-500\">Geo Locator</a>\r\n");
      out.write("                                                                </li>\r\n");
      out.write("                                                            </ul>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- mobile search -->\r\n");
      out.write("                        <div class=\"mobile-search\">\r\n");
      out.write("                            <a href=\"#\" data-toggle=\"modal\" data-target=\"#search-box\"> <i class=\"fas fa-search\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- mobile search -->\r\n");
      out.write("                        <!-- user account -->\r\n");
      out.write("                        <div class=\"user-details p-relative\">\r\n");
      out.write("                            <a href=\"#\" class=\"text-light-white fw-500\">\r\n");
      out.write("                                <img src=\"assets/img/user-1.png\" class=\"rounded-circle\" alt=\"userimg\">--%>\r\n");
      out.write("                              <span>Hi, Kate</span>\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"user-dropdown\">\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"order-details.html\">\r\n");
      out.write("                                            <div class=\"icon\"><i class=\"flaticon-rewind\"></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <span class=\"details\">Past Orders</span>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"order-details.html\">\r\n");
      out.write("                                            <div class=\"icon\"><i class=\"flaticon-takeaway\"></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <span class=\"details\">Upcoming Orders</span>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"#\">\r\n");
      out.write("                                            <div class=\"icon\"><i class=\"flaticon-breadbox\"></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <span class=\"details\">Saved</span>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"#\">\r\n");
      out.write("                                            <div class=\"icon\"><i class=\"flaticon-gift\"></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <span class=\"details\">Gift cards</span>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"#\">\r\n");
      out.write("                                            <div class=\"icon\"><i class=\"flaticon-refer\"></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <span class=\"details\">Refer a friend</span>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"#\">\r\n");
      out.write("                                            <div class=\"icon\"><i class=\"flaticon-diamond\"></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <span class=\"details\">Perks</span>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"#\">\r\n");
      out.write("                                            <div class=\"icon\"><i class=\"flaticon-user\"></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <span class=\"details\">Account</span>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"#\">\r\n");
      out.write("                                            <div class=\"icon\"><i class=\"flaticon-board-games-with-roles\"></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <span class=\"details\">Help</span>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                                <div class=\"user-footer\"><span class=\"text-light-black\">Not Jhon?</span> <a href=\"#\">Sign\r\n");
      out.write("                                    Out</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- mobile search -->\r\n");
      out.write("                        <!-- user notification -->\r\n");
      out.write("                        <div class=\"cart-btn notification-btn\">\r\n");
      out.write("                            <a href=\"#\" class=\"text-light-green fw-700\"> <i class=\"fas fa-bell\"></i>\r\n");
      out.write("                                <span class=\"user-alert-notification\"></span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"notification-dropdown\">\r\n");
      out.write("                                <div class=\"product-detail\">\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <div class=\"img-box\">\r\n");
      out.write("                                            <img src=\"assets/img/shop-1.png\" class=\"rounded\" alt=\"image\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"product-about\">\r\n");
      out.write("                                            <p class=\"text-light-black\">Lil Johnnyâs</p>\r\n");
      out.write("                                            <p class=\"text-light-white\">Spicy Maxican Grill</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"rating-box\">\r\n");
      out.write("                                    <p class=\"text-light-black\">How was your last order ?.</p> <span\r\n");
      out.write("                                        class=\"text-dark-white\"><i class=\"fas fa-star\"></i></span>\r\n");
      out.write("                                    <span class=\"text-dark-white\"><i class=\"fas fa-star\"></i></span>\r\n");
      out.write("                                    <span class=\"text-dark-white\"><i class=\"fas fa-star\"></i></span>\r\n");
      out.write("                                    <span class=\"text-dark-white\"><i class=\"fas fa-star\"></i></span>\r\n");
      out.write("                                    <span class=\"text-dark-white\"><i class=\"fas fa-star\"></i></span>\r\n");
      out.write("                                    <cite class=\"text-light-white\">Ordered 2 days ago</cite>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- user notification -->\r\n");
      out.write("                        <!-- user cart -->\r\n");
      out.write("                        <div class=\"cart-btn cart-dropdown\">\r\n");
      out.write("                            <a href=\"#\" class=\"text-light-green fw-700\"> <i class=\"fas fa-shopping-bag\"></i>\r\n");
      out.write("                                <span class=\"user-alert-cart\">3</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"cart-detail-box\">\r\n");
      out.write("                                <div class=\"card\">\r\n");
      out.write("                                    <div class=\"card-header padding-15\">Your Order</div>\r\n");
      out.write("                                    <div class=\"card-body no-padding\">\r\n");
      out.write("                                        <div class=\"cat-product-box\">\r\n");
      out.write("                                            <div class=\"cat-product\">\r\n");
      out.write("                                                <div class=\"cat-name\">\r\n");
      out.write("                                                    <a href=\"#\">\r\n");
      out.write("                                                        <p class=\"text-light-green\"><span\r\n");
      out.write("                                                                class=\"text-dark-white\">1</span> Chilli Chicken</p>\r\n");
      out.write("                                                        <span class=\"text-light-white\">small, chilli chicken</span>\r\n");
      out.write("                                                    </a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"delete-btn\">\r\n");
      out.write("                                                    <a href=\"#\" class=\"text-dark-white\"> <i\r\n");
      out.write("                                                            class=\"far fa-trash-alt\"></i>\r\n");
      out.write("                                                    </a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"price\"><a href=\"#\" class=\"text-dark-white fw-500\">\r\n");
      out.write("                                                    $2.25\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"cat-product-box\">\r\n");
      out.write("                                            <div class=\"cat-product\">\r\n");
      out.write("                                                <div class=\"cat-name\">\r\n");
      out.write("                                                    <a href=\"#\">\r\n");
      out.write("                                                        <p class=\"text-light-green\"><span\r\n");
      out.write("                                                                class=\"text-dark-white\">1</span> loaded cheese</p> <span\r\n");
      out.write("                                                            class=\"text-light-white\">small, chilli chicken</span>\r\n");
      out.write("                                                    </a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"delete-btn\">\r\n");
      out.write("                                                    <a href=\"#\" class=\"text-dark-white\"> <i\r\n");
      out.write("                                                            class=\"far fa-trash-alt\"></i>\r\n");
      out.write("                                                    </a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"price\"><a href=\"#\" class=\"text-dark-white fw-500\">\r\n");
      out.write("                                                    $2.25\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"cat-product-box\">\r\n");
      out.write("                                            <div class=\"cat-product\">\r\n");
      out.write("                                                <div class=\"cat-name\">\r\n");
      out.write("                                                    <a href=\"#\">\r\n");
      out.write("                                                        <p class=\"text-light-green\"><span\r\n");
      out.write("                                                                class=\"text-dark-white\">1</span> Tortia Chicken</p>\r\n");
      out.write("                                                        <span class=\"text-light-white\">small, chilli chicken</span>\r\n");
      out.write("                                                    </a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"delete-btn\">\r\n");
      out.write("                                                    <a href=\"#\" class=\"text-dark-white\"> <i\r\n");
      out.write("                                                            class=\"far fa-trash-alt\"></i>\r\n");
      out.write("                                                    </a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"price\"><a href=\"#\" class=\"text-dark-white fw-500\">\r\n");
      out.write("                                                    $2.25\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"item-total\">\r\n");
      out.write("                                            <div class=\"total-price border-0\"><span class=\"text-dark-white fw-700\">Items subtotal:</span>\r\n");
      out.write("                                                <span class=\"text-dark-white fw-700\">$9.99</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"empty-bag padding-15\"><a href=\"#\">Empty bag</a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"card-footer padding-15\"><a href=\"checkout.html\"\r\n");
      out.write("                                                                           class=\"btn-first green-btn text-custom-white full-width fw-500\">Proceed\r\n");
      out.write("                                        to Checkout</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- user cart -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-12 mobile-search\">\r\n");
      out.write("                    <div class=\"mobile-address\">\r\n");
      out.write("                        <a href=\"#\" class=\"delivery-add\" data-toggle=\"modal\" data-target=\"#address-box\"> <span\r\n");
      out.write("                                class=\"address\">Brooklyn, NY</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"sorting-addressbox\"><span\r\n");
      out.write("                            class=\"full-address text-light-green\">Brooklyn, NY 10041</span>\r\n");
      out.write("                        <div class=\"btns\">\r\n");
      out.write("                            <div class=\"filter-btn\">\r\n");
      out.write("                                <button type=\"button\"><i class=\"fas fa-sliders-h text-light-green fs-18\"></i>\r\n");
      out.write("                                </button>\r\n");
      out.write("                                <span class=\"text-light-green\">Sort</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"filter-btn\">\r\n");
      out.write("                                <button type=\"button\"><i class=\"fas fa-filter text-light-green fs-18\"></i>\r\n");
      out.write("                                </button>\r\n");
      out.write("                                <span class=\"text-light-green\">Filter</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"main-sec\"></div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
